// Generated by Wrangler by running `wrangler types`

// eslint-disable-next-line @typescript-eslint/no-empty-interface,@typescript-eslint/no-empty-object-type
interface Env {
  TWILIO_ACCOUNT_SID: string;
  TWILIO_AUTH_TOKEN: string;
  GENERATOR_SERVICE: Service<import("../generator/src/index").default>;
  CORE_SERVICE: Service<import("../core-service/src/index").default>;
  CRYPTO_SERVICE: Service<import("../crypto-service/src/index").default>;
  SYSTEM_CACHE: KVNamespace;
}
