# .github/workflows/deploy-dashboard.yml

name: Deploy Dashboard Worker

on:
  push:
    branches:
      - main

permissions:
  contents: read
  deployments: write

jobs:
  deploy-dashboard:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "9.x"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # TURBO BUILD YA ES TASK DEPENDENCIA DE DEPLOY en tu turbo.json,
      # por eso no necesitas 'pnpm turbo run build'
      - name: Deploy Dashboard Worker with Turbo
        run: pnpm turbo run deploy --filter=@worker/dashboard
        env:
          # el secreto tiene que estar definido como "Repository secret"
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Success!
        run: echo "✅ Dashboard Worker desplegado correctamente ✅"
